---
  # QA Gateway
  url: https://qa-api.atom.ktp.io
  defaultPath: h/
  port: 443
  project: Product Config API
  environment: QA
  requestFile: requests.yaml
  apiKey: atomqateam
  tokenSecret: electron